### ISSUE TITLE
Docker images should be regulary updated for security and bug fixes

### ISSUE THREAD

**Issue by btlogy** [LeastAuthority/magic-wormhole-docker#27]
As today, the 3 Docker images in this repository are pinning a specific version of their base image (community maintained [PyPy](https://hub.docker.com/_/pypy) or [Python](https://hub.docker.com/_/python)).
And nothing is in place on our side to update our images when a new version of those base images is available.

Which means our images could become vulnerable for a while before we manually decide to update them (e.g.: with a new version of magic-wormhole).

According to the [FAQ]([https://github.com/docker-library/faq](https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves)) of the Docker Library project, the base images should be regularly updated.
It would be great if we could (automatically) track those updates and re-build our own image when needed.

Alternatively, we may want to pin a intermediate version (e.g.: 3.9 instead of 3.9.16) and/or update faster than the base image by adding something like `RUN apt-get dist-upgrade` (possibly reducing reproducibility and breaking compatibility).

**Comment by meejah** [comment]
At least part of this comment is relevant here too: https://github.com/LeastAuthority/magic-wormhole-docker/issues/26#issuecomment-1540299205

**Comment by btlogy** [comment]
As I was expecting, I see around some similar cases based on Dependabot.
Not that I like it much, but that could be a first simple step, if this works for us.

**Comment by btlogy** [comment]
I've successfully tested Dependabot with Docker (see la-test/sbx-actions#44).

Unfortunately, there is no support (yet) for wild card or recursive lookup, which forces us to enable this feature for each Dockerfile (see dependabot/dependabot-core#2178).
Though, this is not really a big problem in our case.

**Comment by btlogy** [comment]
Yeah: as expected, after merging #29, dependabot has created 2 pull request we can now merge to update those base images:

* #31
* #32
