### ISSUE TITLE
Documentation: Improve Readme

### ISSUE THREAD

**Issue by hacklschorsch** [LeastAuthority/magic-wormhole-docker#4]
Looking at this repo I wasn't sure whether `readme.adoc` is about this repository or copied from somewhere else...

- A short introduction would be nice: What is this? Who is it for? Where is it currently used?
- When I see a headline saying "Basic Instructions" I would expect a manual to get this up and running, not some obscure seeming references to Git versioning and GitHub actions configuration
- I know you like asciidoc, but it's introducting another markup format... is adoc better enough to justify the friction for contributers?
- If there's CI, especially GitHub's own, maybe we can add some of those gimmicky and ever broken SVG badges with links to the latest CI runs? Or just a static image saying "CI failed" for street cred ;)

**Comment by wuan** [comment]
Thank you! This repo was a quick start in order to split all components into separate repos having a proper automated deployment. We will fix the missing information in the following weeks.
